import AppKit

/// Polls the general pasteboard and feeds changes into the history store.
/// Polling (rather than any private notification) is the only reliable,
/// permission-free way to observe pasteboard changes on macOS.
final class PasteboardMonitor {

    private let pasteboard = NSPasteboard.general
    private let prefs: Preferences
    private let history: HistoryStore
    private let imageStore: ImageStore?

    private var timer: Timer?
    private var lastChangeCount: Int

    /// Change counts produced by our own writes, to be skipped so we never
    /// re-capture what we just pasted (CAP-7).
    private var suppressedChangeCounts: Set<Int> = []

    // Concealed / transient / auto-generated markers we must never capture (CAP-3).
    private static let skipTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    private static let maxTextBytes = 1_000_000    // 1MB (STO-4)
    private static let maxImageBytes = 10_000_000  // 10MB (STO-4)

    init(prefs: Preferences, history: HistoryStore, imageStore: ImageStore? = nil) {
        self.prefs = prefs
        self.history = history
        self.imageStore = imageStore
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        // 0.15s poll, on .common so it keeps firing during menu tracking.
        let timer = Timer(timeInterval: 0.15, repeats: true) { [weak self] _ in
            self?.tick()
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Record a change count our own paste caused, so the next tick ignores it.
    func suppress(changeCount: Int) {
        suppressedChangeCounts.insert(changeCount)
        // Keep the set tiny — only the most recent couple of writes matter.
        if suppressedChangeCounts.count > 8 {
            suppressedChangeCounts.removeAll()
            suppressedChangeCounts.insert(changeCount)
        }
    }

    private func tick() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        if suppressedChangeCounts.remove(current) != nil { return }
        if prefs.paused { return }

        capture()
    }

    private func capture() {
        // Type filter first — cheapest rejection (CAP-3).
        let available = pasteboard.types ?? []
        if Self.skipTypes.contains(where: { available.contains($0) }) { return }

        // Exclusion list by frontmost app (CAP-4).
        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        if let source, prefs.excludedBundleIDs.contains(source) { return }

        // Prefer text; fall back to image.
        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            guard string.utf8.count <= Self.maxTextBytes else { return }
            // Optionally skip anything that looks like a secret (PRV-5).
            if prefs.skipSecrets, SecretDetector.looksSecret(string) { return }
            history.insert(.text(string, source: source))
            return
        }

        // Image: try PNG then TIFF (CAP-2). Persist the bytes to the image store
        // immediately and record the on-disk path so the item survives relaunch.
        for type in [NSPasteboard.PasteboardType.png, .tiff] {
            if let data = pasteboard.data(forType: type),
               data.count <= Self.maxImageBytes,
               let image = NSImage(data: data) {
                let hash = ClipboardItem.hash(of: data)
                let path = imageStore?.save(data: data, hash: hash)
                let item = ClipboardItem.persisted(
                    hash: hash, kind: .image, text: nil,
                    imagePath: path, imageWidth: Int(image.size.width),
                    imageHeight: Int(image.size.height), byteSize: data.count,
                    source: source, createdAt: Date()
                )
                history.insert(item)
                return
            }
        }
    }
}
